# Generated by Django 3.2.4 on 2021-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_id', models.IntegerField()),
            ],
            options={
                'ordering': ['like_id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='liked_list',
            field=models.ManyToManyField(to='articleapp.LikedList'),
        ),
    ]
