# Generated by Django 3.2.4 on 2021-07-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_auto_20210712_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='liked_list',
        ),
        migrations.DeleteModel(
            name='LikedList',
        ),
    ]
